# Generated by Django 3.2 on 2021-05-05 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuisine', '0004_alter_recipe_can_be_ingr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('stopped', models.BooleanField(default=False)),
                ('parent_folder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.folder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('stopped', models.BooleanField(default=False)),
                ('price', models.IntegerField()),
                ('serving_time', models.IntegerField()),
                ('pinned', models.BooleanField(default=False)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.folder')),
                ('recipe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cuisine.recipe')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
