# Generated by Django 3.2 on 2021-04-21 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('total_amount', models.DecimalField(decimal_places=6, max_digits=13)),
            ],
        ),
        migrations.CreateModel(
            name='CommodityCategory',
            fields=[
                ('name', models.CharField(default='?', max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CommodityUnit',
            fields=[
                ('name', models.CharField(default='?', max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CompoundIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=13)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ElementaryIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=13)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IngredientUnit',
            fields=[
                ('name', models.CharField(default='?', max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compound_ingredients', models.ManyToManyField(related_name='_cuisine_recipe_compound_ingredients_+', through='cuisine.CompoundIngredient', to='cuisine.Recipe')),
                ('elementary_ingredients', models.ManyToManyField(through='cuisine.ElementaryIngredient', to='cuisine.Commodity')),
            ],
        ),
        migrations.AddField(
            model_name='elementaryingredient',
            name='from_recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuisine.recipe'),
        ),
        migrations.AddField(
            model_name='elementaryingredient',
            name='to_commodity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuisine.commodity'),
        ),
        migrations.AddField(
            model_name='elementaryingredient',
            name='unit',
            field=models.ForeignKey(default='?', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='+', to='cuisine.ingredientunit'),
        ),
        migrations.AddField(
            model_name='compoundingredient',
            name='from_recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuisine.recipe'),
        ),
        migrations.AddField(
            model_name='compoundingredient',
            name='to_recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cuisine.recipe'),
        ),
        migrations.AddField(
            model_name='compoundingredient',
            name='unit',
            field=models.ForeignKey(default='?', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='+', to='cuisine.ingredientunit'),
        ),
        migrations.AddField(
            model_name='commodity',
            name='category',
            field=models.ForeignKey(default='?', on_delete=django.db.models.deletion.SET_DEFAULT, to='cuisine.commoditycategory'),
        ),
        migrations.AddField(
            model_name='commodity',
            name='unit',
            field=models.ForeignKey(default='?', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='+', to='cuisine.commodityunit'),
        ),
    ]
