# Generated by Django 3.2 on 2021-04-21 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='compoundingredient',
            name='to_recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cuisine.recipe', verbose_name='Ingredient'),
        ),
        migrations.AlterField(
            model_name='elementaryingredient',
            name='to_commodity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuisine.commodity', verbose_name='Ingredient'),
        ),
    ]
