# Generated by Django 3.2 on 2021-05-05 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0003_auto_20210422_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='can_be_ingr',
            field=models.BooleanField(default=False, verbose_name='Can be an ingredient'),
        ),
    ]
